import Sidebar from "../components/Sidebar";
import "../styles/globals.css";

export const metadata = {
  title: "Management Panel",
  description: "Generated by Mohammadreza-brz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
