import "../styles/global.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import CartProvider from "../Contexts/CartContext";

export const metadata = {
  title: "Digi Shop",
  description: "Generated by Mohammd-brz",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
